### ISSUE TITLE
Add golangci-lint action for pull requests.

### ISSUE THREAD

**Issue by jpeach** [projectcontour/.github#2]
**Please describe the problem you have**

Add https://github.com/golangci/golangci-lint-action to this repository so that all the repositories in the organization can get it for automatically. One risk is that upgrading the linter version here affects all repositories, but I'm inclined to think that we can like with that.

**Comment by jpeach** [comment]
@Glyphack Are you interested in duplicating https://github.com/projectcontour/contour/pull/2976 to this repository?

**Comment by Glyphack** [comment]
Ofc. @jpeach
